project:
  type: website
  output-dir: docs

website:
  title: "Luke Jimenez"
  navbar:
    left:
      - href: index.qmd
      - project.qmd
    
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/lucas-jimenez-nc/
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/luke-jimenez
 

format:
  html:
    theme: minty  # flatly, litera, lumen, lux, minty, pulse, sandstone, zephyr, quartz, yeti, cosmo, sketchy
    css: styles.css
    toc: true

execute: 
  freeze: auto

